name: Hello Andew Build

on: [push]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version}}
    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v2

    - name: List files
      run: ls -lah

    - name: Bump Version
      id: bump
      uses: radicaldrew/maven-version-bump-action@master
      with:
        github-token: ${{ secrets.github_token }}
        pom-path: "./myapp/"
        type: "patch"
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
        cache: maven
        settings-path: ${{ github.workspace }}
    
    - name: Build with Maven
      run: mvn -B compile --file myapp/pom.xml

    - name: Build a package
      run: mvn -B package --file myapp/pom.xml

    - uses: actions/upload-artifact@v3
      with:
        name: jar-artifact
        path: myapp/target/*.jar
        retention-days: 1

    - name: Print Version
      run: "echo 'New Version: ${{steps.bump.outputs.version}}'"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v3
      with:
          name: jar-artifact
          path: myapp/target/

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
     
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
       images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{needs.build.outputs.version}}, latest
        registry: ${{ env.REGISTRY }}
        dockerfile: Dockerfile.ci
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
     